/// GUI

const SET_POPUP = "OPEN_POPUP";
const PROGRESS_PLAYLIST_GENERATION = "PROGRESS_PLAYLIST_GENERATION";
const BUTTONS_BLOCK = "BUTTONS_BLOCK";
const BUTTONS_UNBLOCK = "BUTTONS_UNBLOCK";

/// Song Level

const LOAD_SONGS = "LOAD_SONGS";
const RESET_LOADED_SONGS = "RESET_LOADED_SONGS";

/// Playlist Level

const MODIFY_PLAYLIST_SCHEMA = "MODIFY_PLAYLIST_SCHEMA";

const ADD_PLAYLIST_SCHEMA = "ADD_PLAYLIST_SCHEMA";
const REMOVE_PLAYLIST_SCHEMA = "REMOVE_PLAYLIST_SCHEMA";

/// API Level

const OBTAIN_AUTH = "OBTAIN_AUTH";

export const {
    SET_POPUP,
    PROGRESS_PLAYLIST_GENERATION,
    BUTTONS_BLOCK,
    BUTTONS_UNBLOCK,

    LOAD_SONGS,
    RESET_LOADED_SONGS,

    MODIFY_PLAYLIST_SCHEMA,
    ADD_PLAYLIST_SCHEMA,
    REMOVE_PLAYLIST_SCHEMA,

    OBTAIN_AUTH,
};